contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bsfetch channel"
    url: https://nfcore.slack.com/channels/bsfetch
    about: Discussion about the nf-core/bsfetch pipeline
